# Generated by Django 2.1.7 on 2019-04-02 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_FBVs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crud',
            old_name='genre',
            new_name='fund_given',
        ),
        migrations.RenameField(
            model_name='crud',
            old_name='title',
            new_name='fund_required',
        ),
        migrations.RemoveField(
            model_name='crud',
            name='user',
        ),
    ]
